### ISSUE TITLE
Add tools required to mount images

### ISSUE THREAD

**Issue by janstarke** [dfir-dd/packer#1]
Could you please add the following packages:

- `afflib-tools`
- `qemu-utils`
- `rhash`
- `liblnk-utils`

**Comment by Explie** [comment]
Added in newest Release
https://portal.cloud.hashicorp.com/services/vagrant/registries/dfir-dd/boxes/kali/versions/2024.3.2?project_id=b18952ef-c9d8-4651-9517-142d90f064b7
